#!/bin/sh

DIR=`dirname $0`

cd $DIR
DIR=`pwd`
LIB=`ls lib/*.jar`

for i in ${LIB}
do
  if [ "$i" != "${LIB}" ] ; then
    CLASSPATH=$CLASSPATH:"$i"
  fi
done

java -classpath $CLASSPATH org.bidib.jbidibc.StopMacro $@
