#!/bin/sh

. set_properties

DIR=`dirname $0`

cd $DIR

RELEASEDIR=`pwd`

echo release directory is $RELEASEDIR

echo switch to local relase base dir: $LOCAL_RELEASE_BASE
mkdir -p $LOCAL_RELEASE_BASE
cd $LOCAL_RELEASE_BASE

echo remove directory: $PROJECT_NAME
rm -fr $PROJECT_NAME > /dev/null

echo checkout $PROJECT_NAME
svn co $SVN_BASE_PATH/$PROJECT_NAME $PROJECT_NAME -q

echo "prepare release $PROJECT_NAME, releaseVersion: $TAG_NAME, next dev version: $NEXT_DEV_VERSION"
cd $PROJECT_NAME
mvn release:clean release:prepare -Dtag=$TAG_NAME -DreleaseVersion=$TAG_NAME -DdevelopmentVersion=$NEXT_DEV_VERSION -Dgpg.passphrase=$PGP_PASSPHRASE

echo "perform release (export, build, deploy)"
mvn release:perform -DconnectionUrl=scm:svn:$SVN_TAGS_PATH/$TAG_NAME -Dgpg.passphrase=$PGP_PASSPHRASE

echo ===============================
echo RELEASE OF $PROJECT_NAME PASSED
echo ===============================

cd $RELEASEDIR
